bank/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bankingapp.urls')),
    path('credential/', include('credential.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankingapp/urls.py
from . import views
from django.urls import path
app_name='bankingapp'
urlpatterns = [
    path('',views.demo,name='demo'),

]

credential/urls.py
from . import views
from django.urls import path
app_name='credential'



urlpatterns = [


    path('login', views.login, name='login'),
    path('register',views.register,name='register'),
    path('submit', views.submit, name='submit'),
    path('logout', views.logout, name='logout'),
    path('forms', views.forms, name='forms'),
]

credential/models.py
# from django.db import models
#
#
# class Bank(models.Model):
#    name = models.CharField(max_length=250)
#
#
#    def __str__(self):
#       return self.name
#

# Create your models here.

bankingapp/views.py
from django.shortcuts import render

# Create your views here.
# from . models import Name
def demo(request):
    # obj=Place.objects.all()
    # obj2=Name.objects.all()
    return render(request,'index.html')

credential/views.py
from django.shortcuts import render
from django.contrib import messages, auth

from django.contrib.auth.models import User
from django.core.mail import message
from django.shortcuts import render, redirect,HttpResponse


# Create your views here.
def login(request):
    if request.method=='POST':
        usernam=request.POST['username']
        passwor= request.POST['password']
        user=auth.authenticate(username=usernam,password=passwor)
        if user is not None:
            auth.login(request,user)
            return render(request,'inde.html')

        else:
            messages.info(request,"invalid credential")
            return redirect("credential:login")
    return render(request,'login.html')
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        # first_name = request.POST['first_name']
        # last_name = request.POST['last_name']
        # email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username taken')
                return redirect('credential:register')
            # elif User.objects.filter(email=email).exists():
            #     messages.info(request,'email taken')
            #     return redirect('register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                return redirect('credential:login')
                print("user registered")
        else:
            messages.info(request,"password not matching")
            return redirect('credential:register')
        return render(request,'inde.html')

    return render(request,'register.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def forms(request):
     # if request.method == 'POST':
     #    name = request.POST.get('name', )
     #    desc = request.POST.get('desc', )
     #    year = request.POST.get('year', )
     #
     #    movie = Movie(name=name, desc=desc, year=year, img=imag)
     #    movie.save()
     #    return redirect('/')
    return render(request, 'forms.html')
def submit(request):
    return render (request,'submit.html')

templates/forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
     <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script language="javascript" type="text/javascript">

    $(document).ready(function() {
        //create arrays to store option and values
        var Ernakulam = [
            {display: "Aluva", value: "aluva" },
            {display: "Edapally", value: "edapally" },

        ];
        var Kannur = [
            {display: "Mahe", value: "mahe" },
            {display: "Payyanur", value: "payyanur" },

        ];
        var Kollam = [
            {display: "Perinad", value: "perinad" },
            {display: "Thrikkaruva", value: "thrikkaruva" },

        ];
        var Kottayam= [
            {display: "Pampady", value: "pampady" },
            {display: "Manarcad", value: "manarcad" },

        ];
        var Malappuram= [
            {display: "Ponnani", value: "ponnani" },
            {display: "Vettom", value: "vettom" },

        ];
        var Trivandrum= [
            {display: "Attingal", value: "attingal" },
            {display: "Nedumangad", value: "nedumangad" },

        ];


        //If parent option is changed
        $("#parent_selection").change(function() {
            var parent = $(this).val(); //get option value from parent
            switch(parent){ //using switch compare selected option and populate child
                case 'Ernakulam':
                    $('#child_selection').attr('disabled', false);
                    list(Ernakulam);
                    break;
                case 'Kannur':
                    $('#child_selection').attr('disabled', false);
                    list(Kannur);
                    break;
                case 'Kollam':
                    $('#child_selection').attr('disabled', false);
                    list(Kollam);
                    break;
                case 'Kottayam':
                    $('#child_selection').attr('disabled', false);
                    list(Kottayam);
                    break;
                case 'Malappuram':
                    $('#child_selection').attr('disabled', false);
                    list(Malappuram);
                    break;
                case 'Trivandrum':
                    $('#child_selection').attr('disabled', false);
                    list(Trivandrum);
                    break;

                default: //default child option is blank
                    $("#child_selection").html('');
                    $('#child_selection').attr("disabled", true);
                    break;
            }
        });

        //function to populate child select box
        function list(array_list) {
            $("#child_selection").html(""); //reset child options
            $(array_list).each(function (i) { //populate child options
                $("#child_selection").append("<option value='" + array_list[i].value + "'>" + array_list[i].display + "</option>");
            });
        }
    });
    </script>


    <title>FORM</title>
</head>

<body>
<h1>APPLICATION FORM</h1>
<br>
<form method="POST" action="{% url 'credential:submit' %}" class="registartion-form" onsubmit="return formValidation()">
 {% csrf_token%}
<label> Firstname </label>
<input type="text" name="firstname" size="15" required> <br> <br>

<label> Lastname: </label>
<input type="text" name="lastname" size="15"  required> <br> <br>
  <label> DOB: </label>

    <input type="date" name="phone" required><br>
<br>




<label>
Gender :
</label><br>
<input type="radio" name="male" id="female" required>
    <label for="female">female</label> <br>
    <input type="radio" name="male" id="male" required>
    <label for="male">Male</label> <br>
    <input type="radio" name="male" id="other" required>
    <label for="other">other</label> <br>
<br>
<br>

<label>
Phone :
</label>
<input type="text" name="country code"  value="+91" size="2"/>
<input type="number" name="phone" size="10" required> <br> <br>
Address
<br>
<textarea cols="80" rows="5" value="address" required>
</textarea>
<br> <br>
Email:
<input type="email" id="email" name="email" required> <br>
<br> <br>
    <label>
    Materials provided :
</label><br>
    <input type="checkbox" name="card" id="debit card" >
    <label for="debit card">debit card</label> <br>
    <input type="checkbox" name="card" id="credit card" >
    <label for="credit card">credit card</label> <br>
    <input type="checkbox" name="card" id="cheque book" >
    <label for="cheque book">cheque book</label> <br>
<br>
<br>
    <label>
Account Type
</label>
<select required>
    <option value="type">--Types--</option>
<option value="savings" >savings</option>
<option value="current" >current</option>

</select>

<br>
<br>
    <div>
<div class="wrapper">
        District:
        <select name="parent_selection" id="parent_selection" required>
            <option value="">-- Please Select --</option>
            <option value="Ernakulam">Ernakulam</option>
            <option value="Kannur">Kannur</option>
            <option value="Kollam">Kollam</option>
            <option value="Kottayam">Kottayam</option>
            <option value="Malappuram">Malappuram</option>
            <option value="Trivandrum">Trivandrum</option>

        </select>
        <select name="child_selection" id="child_selection" disabled="disabled"/>

</div>
    </div>
    <br>
    <br>
        <input type="submit">
    <br>


    <br>
    <div class="mx-auto">
      <a href="{% url 'credential:logout' %}" class="btn btn-secondary btn-block my_custom_button">logout</a>

     </div>




</form>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> LOGIN</title>
</head>
<body style="text-align:center;">
<h1>Login</h1>
<form action="login" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="enter username"><br>
    <br>
    <input type="password" name="password" placeholder="enter password"><br>
    <br>
    <input type="submit">
    <a href="{% url 'credential:register' %}" class="btn btn-secondary"> Register </a>

</form>

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CREDENTIAL</title>
</head>
<body style="text-align:center;">
<h1> Registration </h1>
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="enter your username"><br>
    <br>
    <input type="password" name="password" placeholder="enter your password"><br>
    <br>

    <input type="password" name="password1" placeholder="confirm your password"><br>
    <br>

    <input type="submit"><br>
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</body>
</html>

templates/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="text-align:center;">
<h2>Application successfully accepted</h2>
<div class="mx-auto">
      <a href="{% url 'credential:logout' %}" class="btn btn-secondary btn-block my_custom_button">Exit</a>
</body>
</html>